### ISSUE TITLE
Textarea type not working

### ISSUE THREAD

**Issue by eimantaaas** [bakerkretzmar/nova-settings-tool#12]
Then trying to use field type as textarea the field do not show's up on settings.

`[
                    'key' => 'message',
                    'name' => 'Notification message',
                    'type' => 'textarea',
                    'description' => 'Popup content.',
                ],`

**Comment by MaxRazen** [comment]
I have the same problem
```
    'panels' => [
        // ...
        [
            'name' => 'Advertisement',
            'settings' => [
                [
                    'key' => 'adv_library_code',
                    'name' => 'Advertisement library code',
                    'type' => 'textarea',
                    'description' => 'test',
                ],
            ],
        ],
    ],
```

**Comment by bakerkretzmar** [comment]
I think this is because the package didn't update properly for both of you. I didn't realize [Composer treats 0.x version numbers differently](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators).

I've tagged a 2.1 release, run `composer update` again and this should be fixed.

**Comment by MaxRazen** [comment]
@eimantaaas many thanks, now it works

**Comment by eimantaaas** [comment]
Yes, I can confirm it's working now, thank you!
